### ISSUE TITLE
In Navigation & Mobile First Design maybe add a note to the anchor description

### ISSUE THREAD

**Issue by keegnotrub** [emspace-io/emspace-io.github.io#69]
Maybe we should say something about exactly what characters you can use.  Like the fact you can't use spaces or whatever?

**Comment by fireantrescue** [comment]
Here is the note included in Lesson 1:

_**Note**: I didn’t type a space in-between Lesson and 01. It’s good to get in the habit of leaving out any unnecessary characters such as spaces, punctuation, or any mathematical marks (fraction bars slashes, pluses, minuses, etc) which can confuse the computer and create trouble for your site._

Maybe our anchored link note could be a version of this:

_**Note**: When giving attributes like `id=` a value (you might think of this as naming), as we are doing to create anchored links, we should make sure that those values are seen by the browser as single units. This means that you can use a single word or two or more words if all words are connected by hyphens. Make sure not to use any unnecessary characters such as spaces, punctuation, or any mathematical marks (fraction bars slashes, pluses, minuses, etc) in your value. Adding any of these things will cause errors in your page. It's especially important not to use spaces, as the browser sees spaces as separators between two entirely different things rather than one single unit._
