### ISSUE TITLE
Consider adding css reset at start of lesson 16

### ISSUE THREAD

**Issue by keegnotrub** [emspace-io/emspace-io.github.io#78]
I feel like adding it in the middle kind of breaks me from what I was learning about CSS3

**Comment by fireantrescue** [comment]
I see your point, but I'm hesitant. The reason I've included it in the spot it's currently in is because it seemed like a good teachable moment. Not only do you see that the shadow has a direction, you see that the default margin does get in the way which is often a confusing thing for students. I could just start adding the universal selector reset as part of the boilerplate (I've considered doing that many times), but I keep thinking that it may actually hurt some of the understanding of what is happening...  I'd like to talk this one through a bit more.

The universal selector is first introduced in the box model lesson when I describe margin. Doesn't appear in 9, 10, 11, 12.    Back in 13 (adv positioning) for expanding the teal header background to the browser edges. Not present in 14 (medial queries) . Magically appears in 15 out of nowhere right before the paragraph with fig. 34 reference.

**Comment by keegnotrub** [comment]
Taken care of in #95
